### ISSUE TITLE
Caricamento appunti lezioni

### ISSUE THREAD

**Issue by deneb-alpha** [deneb-alpha/Lab_open_source-2024_2025#2]
# Descrizione

Per ogni lezione caricare in `Appunti-generci` gli appunti della lezione

# Task

- [ ] Caricare in `Lezioni/Argomenti` gli appunti della lezione, utilizzando la sottocartella dedicata
- [ ] La pull request dovrà contenere:
  - [ ] gli appunti
  - [ ] specificare informazioni sul giorno della lezione e gli argomenti trattati
  - [ ] un link al file della licenza dello studente e alla relativa pull request con cui il file è stato caricato
- [ ] Se lo studente non ha ancora creato alcuna pull request in precedenza, anche la issue #1 deve essere completata
